### ISSUE TITLE
As a game maker, I can set a scoring scheme

### ISSUE THREAD

**Issue by teusday** [SBWGroup/eScavenge#27]
Default, later editable

**Comment by Davidmo10** [comment]
#Basic ideas here for now. Will implement later 

#First scoring mode: First to win
#1 point added to total points per second in game. Points stop updating after game ends for them. Team with least points after game is over wins. Prioritizes speed

#Second scoring mode: Team with most points wins.
#Scoring formula (subject to change): As soon as confirmation question is requested, timer begins. Score for that question = 600 - (5 x seconds passed). 
#After 2 minutes (120 seconds), answering the question gains you 0 points, so you have to try and answer as soon as possible. Its okay to answer after 2 minutes,
#You just won't recieve any points for that question. 4 total questions = 2400 max score. Team closest to 2400 wins. Prioritizes accuracy

#Third scoring mode: Team with most correct answers in least tries wins. 
#No points based on time are kept, but a tally of incorrect answers is kept. Team with lowest incorrect answers wins. Tie means tie.

#Fourth scoring mode (possibly merge with 3rd): Team with most correct answers in least tries wins. 
#Points based on time are kept like in first scoring mode. A tally of incorrect answers is kept. Team with lowest incorrect answers wins. Tie of incorrect answers
#means team with least incorrect answers in least amount of time wins.

Just some thoughts.
